name: egnn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - intel-openmp=2019.4
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1d
  - pip=19.3.1
  - pycparser=2.19
  - python=3.7.5
  - pytorch=1.3.1
  - readline=7.0
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11

